In [1]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle

In [2]:
header = ['Mes', 'Dia', 'Hora', 
         'Temperature', 'Wind_Speed', 'Wind_Direction', 'Humidity', 'Air_Density', 'Rain_Status',
         'AreaServico_PMV', 'AreaServico_Temp', 'Circulacao_PMV', 'Circulacao_Temp', 'Casal_PMV', 'Casal_Temp', 'Banheiro_PMV', 'Banheiro_Temp', 'Jardim_PMV', 'Jardim_Temp', 'Solteiro_PMV', 'Solteiro_Temp', 'Sala_PMV', 'Sala_Temp', 'Mezanino_PMV', 'Mezanino_Temp',
         'PortaServicoLeste', 'JanelaServicoSul', 'JanelaCasalNorte', 'PortaCasalOeste', 'JanelaCasalOeste', 'JanelaBanheiroLeste', 'PortaBanheiroOeste', 'JanelaJardimNorte', 'JanelaJardimLeste', 'JanelaSolteiroNorte', 'PortaSolteiroSul', 'JanelaSolteiroSul', 'PortaSalaNorte', 'JanelaSalaNorte', 'PortaSalaLeste', 'JanelaSalaSul', 'JanelaSalaOeste', 'PortaCozinhaLeste', 'JanelaCozinhaSul', 'JanelaMezaninoNorte', 'JanelaMezaninoSul', 'JanelaMezaninoOeste', 'JanelaSegundoSul' 
         ]
header_input = ['Hora', 'Temperature', 'Wind_Speed', 'Wind_Direction', 'Humidity', 'Air_Density', 'Rain_Status',
               'AreaServico_PMV', 'AreaServico_Temp', 'Circulacao_PMV', 'Circulacao_Temp', 'Casal_PMV', 'Casal_Temp', 'Banheiro_PMV', 'Banheiro_Temp', 'Jardim_PMV', 'Jardim_Temp', 'Solteiro_PMV', 'Solteiro_Temp', 'Sala_PMV', 'Sala_Temp', 'Mezanino_PMV', 'Mezanino_Temp'
               ]
header_output = [
                'PortaServicoLeste', 'JanelaServicoSul', 'JanelaCasalNorte', 'PortaCasalOeste', 'JanelaCasalOeste', 'JanelaBanheiroLeste', 'PortaBanheiroOeste', 'JanelaJardimNorte', 'JanelaJardimLeste', 'JanelaSolteiroNorte', 'PortaSolteiroSul', 'JanelaSolteiroSul', 'PortaSalaNorte', 'JanelaSalaNorte', 'PortaSalaLeste', 'JanelaSalaSul', 'JanelaSalaOeste', 'PortaCozinhaLeste', 'JanelaCozinhaSul', 'JanelaMezaninoNorte', 'JanelaMezaninoSul', 'JanelaMezaninoOeste', 'JanelaSegundoSul'
                ]
print len(header)
print (len(header_input))
print (len(header_output))

48
23
23

In [3]:
all1 = pd.read_csv('../Data/Canguçu/simulation_all1.csv')
all0 = pd.read_csv('../Data/Canguçu/simulation_all0.csv')

# MODELO d3:
Qualquer nível de melhora<br>
### Arquivos:
- Modelo aberto<br>
- Modelo fechado<br>
- 30 modelos random

In [5]:
def is_better(dataFrame, it, PMV_label1, PMV_label2):
    """it = iterator"""
    it = int(it)
    if (it > 0 and it < (dataFrame['Hora'].count() - 1)):
        if ((abs(dataFrame.iloc[it - 1][PMV_label1]) >= abs(dataFrame.iloc[it][PMV_label1])) and
            (abs(dataFrame.iloc[it - 1][PMV_label2]) >= abs(dataFrame.iloc[it][PMV_label2]))):
            return True
        else:
            return False
    else:
        return False
    
    #return (dataFrame.iloc(it))

SELECIONA A PARTIR DE **TODAS ABERTAS** E **TODAS FECHADAS**

In [6]:
selected = pd.DataFrame(columns=header)
tot = 0
c = 0

for i in xrange(1, all1['Mes'].count() - 1):
    if (is_better(all1, i, 'Sala_PMV', 'Mezanino_PMV')):
        #print i
        c = c + 1
        selected = selected.append(all1.iloc[i])

print "All_1: " +  str((c * 100.0)/8760.0) + "%" + " | total: " + str(c)


tot = tot + c
c = 0
for i in xrange(1, all0['Mes'].count() - 1):
    if (is_better(all0, i, 'Sala_PMV', 'Mezanino_PMV')):
        #print i
        c = c + 1
        selected = selected.append(all0.iloc[i])

print "All_0: " +  str((c * 100.0)/8760.0) + "%" + " | total: " + str(c)

All_1: 36.1643835616% | total: 3168
All_0: 25.7876712329% | total: 2259

GERA **LISTA** DE ARQUIVOS DE ENTRADA<br>
Por motivos de desempenho:<br>
Caso necessário, alterar e repetir o processo.

In [13]:
testes = ["%03d" % i for i in xrange(21, 31)]
print len(testes)

10

In [14]:
sel = pd.DataFrame(columns=header)
sel.describe()

for arq in testes:
    arquivo = pd.read_csv('../Data/Canguçu/simulation_random_' + str(arq) +'.csv')
    tot = tot + c
    c = 0
    
    for i in xrange(1, arquivo['Mes'].count() - 1):
        if (is_better(arquivo, i, 'Sala_PMV', 'Mezanino_PMV')):
            c = c + 1
            sel = sel.append(arquivo.iloc[i])
    
    print "Random_" + str(arq) + ": " +  str((c * 100.0)/8760.0) + "%" + " | total: " + str(c)

selected = selected.append(sel)

Random_021: 39.0410958904% | total: 3420
Random_022: 38.8926940639% | total: 3407
Random_023: 39.0296803653% | total: 3419
Random_024: 38.3789954338% | total: 3362
Random_025: 39.2465753425% | total: 3438
Random_026: 38.6415525114% | total: 3385
Random_027: 39.1210045662% | total: 3427
Random_028: 39.1552511416% | total: 3430
Random_029: 38.50456621% | total: 3373
Random_030: 38.9840182648% | total: 3415

In [15]:
selected.describe()

,Mes,Dia,Hora,Temperature,Wind_Speed,Wind_Direction,Humidity,Air_Density,Rain_Status,AreaServico_PMV,...,JanelaSalaNorte,PortaSalaLeste,JanelaSalaSul,JanelaSalaOeste,PortaCozinhaLeste,JanelaCozinhaSul,JanelaMezaninoNorte,JanelaMezaninoSul,JanelaMezaninoOeste,JanelaSegundoSul
count,107639.000000,107639.000000,107639.000000,107639.000000,107639.000000,107639.000000,107639.000000,107639.000000,107639.0,107639.000000,...,107639.000000,107639.000000,107639.000000,107639.000000,107639.000000,107639.000000,107639.000000,107639.000000,107639.000000,107639.0
mean,6.583813,15.550813,10.739695,17.058159,4.945322,165.109310,79.227334,1.137285,0.0,-1.975360,...,0.505751,0.504307,0.505108,0.504458,0.503546,0.503193,0.504122,0.503444,0.505154,0.0
std,3.435304,8.733893,5.530459,5.431146,2.020712,103.733231,16.822244,0.029291,0.0,1.140296,...,0.303087,0.303000,0.302742,0.302937,0.302446,0.303383,0.303407,0.302822,0.302819,0.0
min,1.000000,1.000000,0.000000,1.500000,0.400000,1.000000,25.000000,1.065861,0.0,-6.551123,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,4.000000,8.000000,7.000000,12.800000,3.500000,80.000000,66.000000,1.114804,0.0,-2.811637,...,0.240000,0.240000,0.240000,0.240000,0.240000,0.240000,0.240000,0.240000,0.240000,0.0
50%,7.000000,15.000000,11.000000,17.600000,4.800000,138.000000,81.000000,1.133189,0.0,-1.909088,...,0.510000,0.510000,0.510000,0.500000,0.500000,0.500000,0.510000,0.500000,0.510000,0.0
75%,10.000000,23.000000,14.000000,21.200000,6.200000,251.000000,96.000000,1.160018,0.0,-1.123306,...,0.770000,0.770000,0.770000,0.770000,0.770000,0.770000,0.770000,0.770000,0.770000,0.0
max,12.000000,31.000000,23.000000,31.300000,17.400000,360.000000,99.000000,1.222623,0.0,0.958425,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0

In [16]:
total = shuffle(selected)

input_file = total[header_input]
output_file = total[header_output]

total.to_csv("Selected/d03_total.csv", index=False)
input_file.to_csv("Selected/d03_input.csv", index=False)
output_file.to_csv("Selected/d03_output.csv", index=False)

# MODELO d5:
Melhora significativa 10% ou mais de conforto entre a hora anterior e o presente momento<br>
### Arquivos:
- Modelo aberto<br>
- Modelo fechado<br>
- 150 modelos random<br>
- Sistema Especialista

In [3]:
def is_better_sig(dataFrame, it, PMV_label1, PMV_label2):
    """it = iterator"""
    it = int(it)
    if (it > 0 and it < (dataFrame['Hora'].count() - 1)):
        if (((abs(dataFrame.iloc[it - 1][PMV_label1]) - abs(dataFrame.iloc[it][PMV_label1])) >= (abs(dataFrame.iloc[it][PMV_label1]) * 0.1)) and
            ((abs(dataFrame.iloc[it - 1][PMV_label2]) - abs(dataFrame.iloc[it][PMV_label2])) >= (abs(dataFrame.iloc[it][PMV_label2]) * 0.1))):
            return True
        else:
            return False
    else:
        return False

In [4]:
selected = pd.DataFrame(columns=header)

tot = 0
c = 0

In [6]:
SE = pd.read_csv('../Data/Canguçu/simulation_SE_001.csv')

for i in xrange(1, SE['Mes'].count() - 1):
    if (is_better_sig(SE, i, 'Sala_PMV', 'Mezanino_PMV')):
        #print i
        c = c + 1
        selected = selected.append(SE.iloc[i])

print "SE: " +  str((c * 100.0)/8760.0) + "%" + " | total: " + str(c)

SE: 15.9589041096% | total: 1398

In [13]:
for i in xrange(1, all1['Mes'].count() - 1):
    if (is_better_sig(all1, i, 'Sala_PMV', 'Mezanino_PMV')):
        #print i
        c = c + 1
        selected = selected.append(all1.iloc[i])

print "All_1: " +  str((c * 100.0)/8760.0) + "%" + " | total: " + str(c)


tot = tot + c
c = 0
for i in xrange(1, all0['Mes'].count() - 1):
    if (is_better_sig(all0, i, 'Sala_PMV', 'Mezanino_PMV')):
        #print i
        c = c + 1
        selected = selected.append(all0.iloc[i])

print "All_0: " +  str((c * 100.0)/8760.0) + "%" + " | total: " + str(c)

All_1: 10.9474885845% | total: 959
All_0: 5.70776255708% | total: 500

In [63]:
testes = ["%03d" % i for i in xrange(141, 151)]
print len(testes)

10

In [64]:
sel = pd.DataFrame(columns=header)
sel.describe()

for arq in testes:
    arquivo = pd.read_csv('../Data/Canguçu/simulation_random_' + str(arq) +'.csv')
    tot = tot + c
    c = 0
    
    for i in xrange(1, arquivo['Mes'].count() - 1):
        if (is_better_sig(arquivo, i, 'Sala_PMV', 'Mezanino_PMV')):
            c = c + 1
            sel = sel.append(arquivo.iloc[i])
    
    print "Random_" + str(arq) + ": " +  str((c * 100.0)/8760.0) + "%" + " | total: " + str(c)

selected = selected.append(sel)

Random_141: 11.6780821918% | total: 1023
Random_142: 11.8607305936% | total: 1039
Random_143: 11.7351598174% | total: 1028
Random_144: 11.8150684932% | total: 1035
Random_145: 11.8378995434% | total: 1037
Random_146: 11.598173516% | total: 1016
Random_147: 11.5410958904% | total: 1011
Random_148: 11.7351598174% | total: 1028
Random_149: 11.6780821918% | total: 1023
Random_150: 11.8264840183% | total: 1036

In [65]:
selected.describe()

,Mes,Dia,Hora,Temperature,Wind_Speed,Wind_Direction,Humidity,Air_Density,Rain_Status,AreaServico_PMV,...,JanelaSalaNorte,PortaSalaLeste,JanelaSalaSul,JanelaSalaOeste,PortaCozinhaLeste,JanelaCozinhaSul,JanelaMezaninoNorte,JanelaMezaninoSul,JanelaMezaninoOeste,JanelaSegundoSul
count,156674.000000,156674.000000,156674.000000,156674.000000,156674.000000,156674.000000,156674.000000,156674.000000,156674.0,156674.000000,...,156674.000000,156674.000000,156674.000000,156674.000000,156674.000000,156674.000000,156674.000000,156674.000000,156674.000000,156674.0
mean,5.794701,16.715390,11.301569,21.426006,4.652117,181.403258,70.319970,1.115957,0.0,-1.177960,...,0.502027,0.500812,0.501296,0.502227,0.499622,0.500413,0.501162,0.501866,0.501810,0.0
std,3.829788,8.892414,4.234670,3.848446,1.904489,112.114150,15.474199,0.020970,0.0,0.856635,...,0.291289,0.291171,0.291123,0.291211,0.291642,0.290895,0.291282,0.291553,0.291027,0.0
min,1.000000,1.000000,0.000000,1.500000,0.400000,1.000000,25.000000,1.065885,0.0,-6.145238,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,2.000000,9.000000,9.000000,19.600000,3.200000,84.000000,58.000000,1.101247,0.0,-1.682634,...,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.0
50%,5.000000,17.000000,11.000000,22.100000,4.500000,156.000000,70.000000,1.113253,0.0,-1.050437,...,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.0
75%,10.000000,25.000000,13.000000,24.100000,5.800000,307.000000,81.000000,1.126007,0.0,-0.582056,...,0.750000,0.750000,0.750000,0.760000,0.750000,0.750000,0.750000,0.760000,0.750000,0.0
max,12.000000,31.000000,23.000000,31.300000,15.300000,360.000000,99.000000,1.222535,0.0,0.958425,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0

In [66]:
total = shuffle(selected)

input_file = total[header_input]
output_file = total[header_output]

total.to_csv("Selected/d05_total.csv", index=False)
input_file.to_csv("Selected/d05_input.csv", index=False)
output_file.to_csv("Selected/d05_output.csv", index=False)