In [1]:
import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras import optimizers
from keras.models import load_model

np.random.seed(7)

%run Python/simulation.py
%run Python/dataNumpy.py
import sys

from sklearn.preprocessing import Normalizer

Using TensorFlow backend.

In [2]:
headerInput = ['Hora', 'Temperature', 'Wind_Speed', 'Wind_Direction', 'Humidity', 'Air_Density', 'Rain_Status', 'Jardim_PMV','Jardim_Temp','Sala_PMV','Sala_Temp','Mezanino_PMV','Mezanino_Temp']
headerOutput = ['PortaSalaNorte','JanelaSalaNorte','PortaSalaLeste','JanelaSalaSul','JanelaSalaOeste','PortaCozinhaLeste','JanelaCozinhaSul','JanelaMezaninoNorte','JanelaMezaninoSul','JanelaMezaninoOeste']

print(len(headerInput))
print(len(headerOutput))

13
10

In [3]:
Input = pd.read_csv("Selected/v01_input.csv")
Output = pd.read_csv("Selected/v01_output.csv")

Input_pd = Input[headerInput]
Output_pd = Output[headerOutput]

scaler_in = Normalizer().fit(Input_pd)
Input_Norm = scaler_in.transform(Input_pd)

#scaler_out = Normalizer().fit(Output_pd)
#Output_Norm = scaler_out.transform(Output_pd)

Output_Norm = np.array(Output_pd)

print("Data Set: " + str(Input_Norm.shape[0]))
print("Training Set [70%]: "+ str(int(Input_Norm.shape[0]*0.7)+1) )
print("Test Set[30%]: " + str(int(Output_Norm.shape[0]*0.3))+ "\n")


X_training = Input_Norm[:-int(Input_Norm.shape[0]*0.3)]
Y_training = Output_Norm[:-int(Output_Norm.shape[0]*0.3)]

X_test = Input_Norm[int((Input_Norm.shape[0]*0.7)+1):]
Y_test = Output_Norm[int( (Output_Norm.shape[0]*0.7)+1) :]

print "X_training.shape: " + str(X_training.shape)
print "Y_training.shape: " + str(Y_training.shape)
print "X_test.shape: " + str(X_test.shape)
print "Y_test.shape: " + str(Y_test.shape)

Data Set: 37986
Training Set [70%]: 26591
Test Set[30%]: 11395

X_training.shape: (26591, 13)
Y_training.shape: (26591, 10)
X_test.shape: (11395, 13)
Y_test.shape: (11395, 10)

In [ ]:
verao = np.array([])

In [ ]:


outVerao = model.predict(np_inputRN, verbose=0)
outInverno

In [5]:
header = ['Mes', 'Dia', 'Hora', 
         'Temperature', 'Wind_Speed', 'Wind_Direction', 'Humidity', 'Air_Density', 'Rain_Status',
         'AreaServico_PMV', 'AreaServico_Temp', 'Circulacao_PMV', 'Circulacao_Temp', 'Casal_PMV', 'Casal_Temp', 'Banheiro_PMV', 'Banheiro_Temp', 'Jardim_PMV', 'Jardim_Temp', 'Solteiro_PMV', 'Solteiro_Temp', 'Sala_PMV', 'Sala_Temp', 'Mezanino_PMV', 'Mezanino_Temp',
         'PortaServicoLeste', 'JanelaServicoSul', 'JanelaCasalNorte', 'PortaCasalOeste', 'JanelaCasalOeste', 'JanelaBanheiroLeste', 'PortaBanheiroOeste', 'JanelaJardimNorte', 'JanelaJardimLeste', 'JanelaSolteiroNorte', 'PortaSolteiroSul', 'JanelaSolteiroSul', 'PortaSalaNorte', 'JanelaSalaNorte', 'PortaSalaLeste', 'JanelaSalaSul', 'JanelaSalaOeste', 'PortaCozinhaLeste', 'JanelaCozinhaSul', 'JanelaMezaninoNorte', 'JanelaMezaninoSul', 'JanelaMezaninoOeste', 'JanelaSegundoSul' 
         ]
header_input = ['Hora', 'Temperature', 'Wind_Speed', 'Wind_Direction', 'Humidity', 'Air_Density', 'Rain_Status',
               'AreaServico_PMV', 'AreaServico_Temp', 'Circulacao_PMV', 'Circulacao_Temp', 'Casal_PMV', 'Casal_Temp', 'Banheiro_PMV', 'Banheiro_Temp', 'Jardim_PMV', 'Jardim_Temp', 'Solteiro_PMV', 'Solteiro_Temp', 'Sala_PMV', 'Sala_Temp', 'Mezanino_PMV', 'Mezanino_Temp'
               ]

In [9]:
all0 = pd.read_csv('Simulacao/simulation_all0.csv')

In [10]:
all0 = all0[['Mes','Dia']+header_input]

In [11]:
all0.describe()

,Mes,Dia,Hora,Temperature,Wind_Speed,Wind_Direction,Humidity,Air_Density,Rain_Status,AreaServico_PMV,...,Banheiro_PMV,Banheiro_Temp,Jardim_PMV,Jardim_Temp,Solteiro_PMV,Solteiro_Temp,Sala_PMV,Sala_Temp,Mezanino_PMV,Mezanino_Temp
count,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,...,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000
mean,6.526027,15.720548,11.500000,19.547648,2.449098,150.917808,75.947945,1.170664,0.010845,0.172128,...,0.063398,24.629852,1.228146,28.844648,-1.400663,25.763073,0.092948,25.546877,0.897923,27.752177
std,3.448048,8.796749,6.922582,6.038127,2.218589,103.558459,16.187339,0.034159,0.103578,0.613674,...,0.881017,3.547468,1.028681,3.698140,0.523797,0.708457,0.429148,0.965613,0.937587,3.565293
min,1.000000,1.000000,0.000000,-1.200000,0.000000,0.000000,16.000000,1.089685,0.000000,-2.067315,...,-2.473315,13.257172,-1.628275,17.577980,-5.367233,18.019562,-2.316331,17.988054,-1.978839,17.999327
25%,4.000000,8.000000,5.750000,15.200000,1.200000,90.000000,64.000000,1.144752,0.000000,-0.238003,...,-0.589331,21.942097,0.527350,26.582299,-1.711632,25.990458,-0.096385,25.636232,0.242945,25.129487
50%,7.000000,16.000000,11.500000,20.000000,2.100000,140.000000,79.000000,1.165789,0.000000,0.243145,...,0.089856,24.779663,1.202354,28.925979,-1.463438,25.996798,0.135199,25.991102,0.917961,28.029560
75%,10.000000,23.000000,17.250000,24.000000,3.100000,230.000000,89.000000,1.195740,0.000000,0.658047,...,0.741541,27.537628,1.847725,30.954372,-0.963855,25.999138,0.334286,25.997345,1.552710,30.404257
max,12.000000,31.000000,23.000000,36.700000,49.300000,360.000000,100.000000,1.290899,1.000000,1.478031,...,2.347551,32.489072,4.942966,43.174869,-0.380353,26.122727,1.073473,26.831863,3.453343,37.177445

In [20]:
all0['Temperature'].idxmax()

3785

In [17]:
all0.groupby(['Mes'])['Temperature'].describe()

      count       mean       std   min     25%    50%     75%   max
Mes
1.0   744.0  24.834677  3.934471  14.5  22.000  24.40  27.700  36.0
2.0   672.0  23.877381  2.987644  15.5  21.875  24.00  25.900  32.8
3.0   744.0  22.397984  4.446610  11.0  19.500  22.20  25.400  34.4
4.0   720.0  20.219306  4.883021   4.7  17.300  20.35  23.300  32.0
5.0   744.0  15.302554  4.715038   4.0  11.900  15.25  18.700  29.5
6.0   720.0  15.292917  6.791844  -1.2  10.200  13.95  20.600  36.7
7.0   744.0  15.050269  5.528151  -0.5  11.400  14.70  18.300  29.0
8.0   744.0  17.207392  6.124345   0.8  13.200  15.95  21.325  33.2
9.0   720.0  16.280139  5.442889   5.0  12.500  15.70  18.625  34.0
10.0  744.0  19.171640  4.593994   7.0  16.100  19.00  22.000  34.8
11.0  720.0  21.315278  3.946846  10.8  18.800  21.05  24.300  32.0
12.0  744.0  23.877285  4.062126  11.0  20.900  23.60  26.700  34.8

In [19]:
all0.groupby(['Mes'])['Sala_Temp'].describe()

,count,mean,std,min,25%,50%,75%,max
Mes,,,,,,,,
1.0,744.0,25.910324,0.423516,19.740288,25.989363,25.993977,25.997289,26.127360
2.0,672.0,25.990341,0.025718,25.516065,25.987398,25.992631,25.996363,26.040139
3.0,744.0,25.876852,0.383591,23.437343,25.986522,25.992340,25.996941,26.047975
4.0,720.0,25.731205,0.629104,22.349335,25.896380,25.993604,25.998236,26.074238
5.0,744.0,25.108548,1.279815,17.988054,24.534778,25.709284,25.991994,26.101478
6.0,720.0,24.787809,1.392546,19.787278,23.811186,25.330574,25.993796,26.221711
7.0,744.0,25.112457,1.348280,19.550401,24.631318,25.869003,25.998154,26.298256
8.0,744.0,25.324395,1.208075,19.375427,25.103188,25.986466,25.998734,26.690061
9.0,720.0,25.249424,1.089780,21.030965,24.675609,25.868921,25.997595,26.831863
10.0,744.0,25.684863,0.584794,23.037928,25.661902,25.989210,25.997720,26.468781
11.0,720.0,25.842126,0.419615,23.678389,25.978131,25.994465,25.997657,26.171538
12.0,744.0,25.968490,0.140498,24.584836,25.990184,25.994622,25.997525,26.184527

In [18]:
all0.groupby(['Mes'])['Sala_PMV'].describe()

,count,mean,std,min,25%,50%,75%,max
Mes,,,,,,,,
1.0,744.0,0.113094,0.304706,-2.316331,0.082505,0.171806,0.260385,0.506045
2.0,672.0,0.138266,0.119007,-0.246572,0.064525,0.139889,0.214204,0.477894
3.0,744.0,0.014038,0.305532,-1.180172,-0.035489,0.104038,0.200144,0.473992
4.0,720.0,0.573137,0.336439,-0.611211,0.483485,0.686933,0.796331,1.073473
5.0,744.0,0.180600,0.403301,-1.516853,-0.004854,0.220036,0.441795,0.871943
6.0,720.0,0.007964,0.535990,-1.528302,-0.361654,0.021118,0.509878,0.937296
7.0,744.0,0.110934,0.478104,-1.580677,-0.135693,0.269264,0.435859,0.750202
8.0,744.0,0.249451,0.473454,-1.650927,0.093832,0.300059,0.566449,1.013641
9.0,720.0,0.186952,0.396093,-1.075233,-0.022165,0.253630,0.449599,1.012873
10.0,744.0,-0.391443,0.362219,-1.588281,-0.653636,-0.335427,-0.104905,0.302128
11.0,720.0,-0.167222,0.277760,-1.243057,-0.248277,-0.103617,0.001897,0.296890
12.0,744.0,0.111378,0.174820,-0.570964,0.020116,0.121664,0.227769,0.514670

In [23]:
all0.groupby(['Mes'])['Sala_PMV'].idxmin()

Mes
1.0        1
2.0      872
3.0     1689
4.0     2505
5.0     3408
6.0     4257
7.0     5073
8.0     5097
9.0     6201
10.0    6609
11.0    7522
12.0    8072
Name: Sala_PMV, dtype: int64

In [28]:
all0.groupby(['Mes'])['Sala_Temp'].idxmax()

Mes
1.0      733
2.0     1398
3.0     1787
4.0     2337
5.0     2999
6.0     3873
7.0     4814
8.0     5470
9.0     6266
10.0    7142
11.0    7878
12.0    8146
Name: Sala_Temp, dtype: int64

In [26]:
all0.iloc[872]

Mes                  2.000000
Dia                  6.000000
Hora                 8.000000
Temperature         17.600000
Wind_Speed           1.500000
Wind_Direction      50.000000
Humidity            75.000000
Air_Density          1.186291
Rain_Status          0.000000
AreaServico_PMV      0.314631
AreaServico_Temp    26.863561
Circulacao_PMV       0.265593
Circulacao_Temp     26.540598
Casal_PMV           -0.248158
Casal_Temp          29.652278
Banheiro_PMV         0.193917
Banheiro_Temp       26.743677
Jardim_PMV           0.415906
Jardim_Temp         27.380825
Solteiro_PMV        -1.734384
Solteiro_Temp       25.995322
Sala_PMV            -0.246572
Sala_Temp           25.783718
Mezanino_PMV         0.352191
Mezanino_Temp       27.277134
Name: 872, dtype: float64